### PR TITLE
Remove react Images

### PR DESCRIPTION
**Pull request by cordelia-payson**
in public folder 
-deleted logo192.png
- deleted logo512.png

in src folder
- deleted logo.svg (spinning react logo) and removed related lines of code in App.js

### CODE REVIEW

**Comment by Therason** [comment]
Looks good! I definitely agree with getting rid of those images. 👍

This PR does add a `.vscode` directory, so I wanted to ask what the `git.ignoreLimitWarning` option does and if it needs to be pushed to the repo. If it's an option in VS Code that we all need enabled, then I think it should be good to include! Otherwise, maybe we could add the `.vscode` directory to `.gitignore`? 

(also can we remove the `gladiolous` directory on this PR too? It seems like a good place to do so instead of another ticket 😅)

**Review by Therason — CHANGES_REQUESTED** [review]
Looks good! I definitely agree with getting rid of those images. 👍

This PR does add a .vscode directory, so I wanted to ask what the git.ignoreLimitWarning option does and if it needs to be pushed to the repo. If it's an option in VS Code that we all need enabled, then I think it should be good to include! Otherwise, maybe we could add the .vscode directory to .gitignore?

(also can we remove the gladiolous directory on this PR too? It seems like a good place to do so instead of another ticket 😅)

**Comment by cordelia-payson** [comment]
@Therason As far as I can tell the git.ignoreLimitWarning comes from committing a large number of files? I think it is connected to that popup I got last night about having too many files and git not being able to handle all of them. Based on my research it doesn't seem necessary so I will delete it. 
I also removed the gladiolous file (and hopefully it doesn't reappear!)

**Review by Therason — APPROVED** [review]
Awesome, looks good!

**Pull request merged**
