### PR TITLE
Set up basic file structure

### PR DESCRIPTION
**Pull request by cordelia-payson**
Set up basic file structure, imported React to each file, imported relevant components to files

### CODE REVIEW

**Comment by cordelia-payson** [comment]
[set up reviews file structure](https://trello.com/c/qhoLBg6f/70-set-up-reviews-file-structure)

**Review by Therason — CHANGES_REQUESTED** [review]
The structure looks good! The only part I have questions about are changes to the scripts in `package.json`. Do we want to add the `--watch` flag to jest by default? If not, then maybe just make it a separate script called `test:watch` so the default behavior is to run the tests once while keeping the ability to run the tests with the watch flag if needed (or the other way around, depending on what you think). 

For the `server` script, I don't think we need the `--watch` flag. It looks like that option is used to [specify directories nodemon should watch for changes in](https://github.com/remy/nodemon#monitoring-multiple-directories). I think we'd want to watch for changes in all directories, which is the default behavior, so that flag probably isn't needed.

**Comment by cordelia-payson** [comment]
thanks for the input! You are definitely right about the --watch part. I removed it from the server and jest scripts

**Review by Therason — APPROVED** [review]
Awesome! Looks good to merge then 😄

**Pull request merged**
